# Generated by Django 2.1.3 on 2018-12-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20181205_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='alert',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
